import type { Metadata } from "next";
import { AuthProvider } from "@/context/authContext";
import { Inter } from "next/font/google";
import "./globals.css";
import GoogleMapsLoader from "../components/GoogleMapsLoader/GoogleMapsLoader";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const apiKey =
  typeof process.env.GOOGLE_MAPS_API_KEY === "string"
    ? process.env.GOOGLE_MAPS_API_KEY
    : "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleMapsLoader apiKey={apiKey} />
      <head>
        {/* <script
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCqte0pRrcMdfXdMrX4TbTo_HJL3btlTyc&libraries=places"
          async
          defer
        ></script> */}
      </head>
      <body>
        <AuthProvider>
          <main className={inter.className}>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
